<?php
	/*
	* API file untuk aplikasi jaim
	* method untuk data pendapatan
	*/
	require_once 'includes/config.php';
	require_once 'includes/database.php';
	
	$r	= isset($_GET['r']) ? $_GET['r'] : '';
	$p	= isset($_GET['p']) ? $_GET['p'] : '';
	$p1	= isset($_GET['p1']) ? $_GET['p1'] : '';
	$p2 = isset($_GET['p2']) ? $_GET['p2'] : '';
	$p3 = isset($_GET['p3']) ? $_GET['p3'] : '';
	$p4 = isset($_GET['p4']) ? $_GET['p4'] : '';
	$p5 = isset($_GET['p5']) ? $_GET['p5'] : '';
	$p6 = isset($_GET['p6']) ? $_GET['p6'] : '';
	$p7 = isset($_GET['p7']) ? $_GET['p7'] : '';
	
	$DB = new Database(C_USER_DB_JLINDO, C_PASS_DB_JLINDO, C_DB_JLINDO);
	
	/*===== tarik data pendapatan agen pribadi =====*/
	if (strcasecmp($r, '1') == 0) {
		$sql = "SELECT PREFIXPERTANGGUNGAN, NOPERTANGGUNGAN, a.NOAGEN, c.NAMAKLIEN1, NOREKENING, NAMAKOMISIAGEN, 
					CASE WHEN KDJENISCB = 'B' THEN 'Berkala' WHEN KDJENISCB = 'X' THEN 'Sekaligus' ELSE KDJENISCB END CARABAYAR, 
					THNKOMISI, NVL(KOMISIAGENRP, 0) KOMISIAGENRP, TO_CHAR(a.TGLBOOKED, 'DD/MM/YYYY') TGLBOOKED, 
					TO_CHAR(a.TGLPROSES, 'DD/MM/YYYY') TGLPROSES 
				FROM TABEL_404_KOMISI_AGEN a 
				INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN 
				INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
				INNER JOIN TABEL_402_KODE_KOMISI_AGEN d ON a.KDKOMISIAGEN = d.KDKOMISIAGEN 
				WHERE a.KDKOMISIAGEN != '10' AND KDAUTHORISASI = '2' AND a.KDRAYONPENAGIHAN = '$p' 
					AND a.NOAGEN = '$p2' AND a.TGLUPDATED BETWEEN TO_DATE('$p3', 'DD/MM/YYYY') 
					AND TO_DATE('$p4', 'DD/MM/YYYY')
					
				UNION ALL
				
				SELECT NULL, NULL, a.NOAGEN, c.NAMAKLIEN1, NOREKENING, NAMAKOMISIAGEN, NULL, NULL, NILAIPENDAPATAN, NULL, 
					TO_CHAR(a.TGLPROSES, 'DD/MM/YYYY') TGLPROSES 
					FROM TABEL_404_PENDAPATAN_LAIN_AGEN a 
					INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN AND a.KDKANTOR = b.KDKANTOR 
					INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
					INNER JOIN TABEL_402_KODE_KOMISI_AGEN d ON a.KDKOMISIAGEN = d.KDKOMISIAGEN 
					WHERE KDAUTHORISASI = 1 AND a.KDKANTOR = '$p' AND a.NOAGEN = '$p2' 
						AND a.TGLPROSES BETWEEN TO_DATE('$p3', 'DD/MM/YYYY') AND TO_DATE('$p4', 'DD/MM/YYYY')
				
				ORDER BY TGLPROSES, TGLBOOKED";
		
		$DB->parse($sql);
		$DB->execute();
		
		echo json_encode($DB->result());
		//echo $sql;
	}
	
	
	/*===== tarik data pendapatan agen per cabang =====*/
	if (strcasecmp($r, '2') == 0) {
		$sql = "SELECT PREFIXAGEN, NOAGEN, NAMAKLIEN1, KDJABATANAGEN, NAMAJABATANAGEN, NOREKENING, 
					SUM(KOMISIAGENRP) KOMISIAGENRP, KDAREAOFFICE, NAMAAREAOFFICE, KDUNITPRODUKSI, 
					NAMAUNITPRODUKSI, URUTAN
				FROM (
					SELECT b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						NVL(SUM(KOMISIAGENRP), 0) KOMISIAGENRP, b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, 
						f.NAMAUNITPRODUKSI, d.URUTAN 
					FROM TABEL_404_KOMISI_AGEN a 
					INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN 
					INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
					LEFT OUTER JOIN TABEL_413_JABATAN_AGEN d ON b.KDJABATANAGEN = d.KDJABATANAGEN 
					LEFT OUTER JOIN TABEL_410_AREA_OFFICE e ON b.KDAREAOFFICE = e.KDAREAOFFICE AND b.KDKANTOR = e.KDKANTOR 
					LEFT OUTER JOIN TABEL_410_KODE_UNIT_PRODUKSI f ON b.KDKANTOR = f.KDKANTOR AND b.KDAREAOFFICE = f.KDAREAOFFICE 
						AND b.KDUNITPRODUKSI = f.KDUNITPRODUKSI 
					WHERE a.KDKOMISIAGEN != '10' AND KDAUTHORISASI = '2' AND a.KDRAYONPENAGIHAN = '$p' 
						AND a.TGLUPDATED BETWEEN TO_DATE('$p1', 'DD/MM/YYYY') AND TO_DATE('$p2', 'DD/MM/YYYY')
						AND b.KDJABATANAGEN NOT IN ('07', '15')
						AND b.KDSTATUSAGEN = '01'
					GROUP BY b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, f.NAMAUNITPRODUKSI, d.URUTAN 
					
					UNION ALL
					
					SELECT b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						NVL(SUM(NILAIPENDAPATAN), 0) KOMISIAGENRP, b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, 
						f.NAMAUNITPRODUKSI, d.URUTAN 
					FROM TABEL_404_PENDAPATAN_LAIN_AGEN a 
					INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN AND a.KDKANTOR = b.KDKANTOR 
					INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
					LEFT OUTER JOIN TABEL_413_JABATAN_AGEN d ON b.KDJABATANAGEN = d.KDJABATANAGEN 
					LEFT OUTER JOIN TABEL_410_AREA_OFFICE e ON b.KDAREAOFFICE = e.KDAREAOFFICE AND b.KDKANTOR = e.KDKANTOR 
					LEFT OUTER JOIN TABEL_410_KODE_UNIT_PRODUKSI f ON b.KDKANTOR = f.KDKANTOR AND b.KDAREAOFFICE = f.KDAREAOFFICE 
						AND b.KDUNITPRODUKSI = f.KDUNITPRODUKSI 
					WHERE KDAUTHORISASI = 1 AND a.KDKANTOR = '$p' AND a.TGLPROSES BETWEEN TO_DATE('$p1', 'DD/MM/YYYY') 
						AND TO_DATE('$p2', 'DD/MM/YYYY') AND b.KDJABATANAGEN NOT IN ('07', '15')
						AND b.KDSTATUSAGEN = '01'
					GROUP BY b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						a.NILAIPENDAPATAN, b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, f.NAMAUNITPRODUKSI, d.URUTAN
				) temp 
				GROUP BY PREFIXAGEN, NOAGEN, NAMAKLIEN1, KDJABATANAGEN, NAMAJABATANAGEN, NOREKENING, KDAREAOFFICE, 
					NAMAAREAOFFICE, KDUNITPRODUKSI, NAMAUNITPRODUKSI, URUTAN 
				ORDER BY URUTAN ASC, KDAREAOFFICE ASC NULLS FIRST, KDUNITPRODUKSI ASC NULLS FIRST";
		
		$DB->parse($sql);
		$DB->execute();
		
		echo json_encode($DB->result());
		//echo $sql;
	}
	
	
	/*===== tarik data pendapatan agen per wilayah =====*/
	if (strcasecmp($r, '3') == 0) {
		$sql = "SELECT PREFIXAGEN, NOAGEN, NAMAKLIEN1, KDJABATANAGEN, NAMAJABATANAGEN, NOREKENING, 
					SUM(KOMISIAGENRP) KOMISIAGENRP, KDAREAOFFICE, NAMAAREAOFFICE, KDUNITPRODUKSI, 
					NAMAUNITPRODUKSI, URUTAN
				FROM (
					SELECT b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						NVL(SUM(KOMISIAGENRP), 0) KOMISIAGENRP, b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, 
						f.NAMAUNITPRODUKSI, d.URUTAN 
					FROM TABEL_404_KOMISI_AGEN a 
					INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN 
					INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
					LEFT OUTER JOIN TABEL_413_JABATAN_AGEN d ON b.KDJABATANAGEN = d.KDJABATANAGEN 
					LEFT OUTER JOIN TABEL_410_AREA_OFFICE e ON b.KDAREAOFFICE = e.KDAREAOFFICE AND b.KDKANTOR = e.KDKANTOR 
					LEFT OUTER JOIN TABEL_410_KODE_UNIT_PRODUKSI f ON b.KDKANTOR = f.KDKANTOR AND b.KDAREAOFFICE = f.KDAREAOFFICE 
						AND b.KDUNITPRODUKSI = f.KDUNITPRODUKSI 
					WHERE a.KDKOMISIAGEN != '10' AND KDAUTHORISASI = '2' AND a.KDRAYONPENAGIHAN = '$p' 
						AND a.TGLUPDATED BETWEEN TO_DATE('$p1', 'DD/MM/YYYY') AND TO_DATE('$p2', 'DD/MM/YYYY')
						AND b.KDSTATUSAGEN = '01'
					GROUP BY b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, f.NAMAUNITPRODUKSI, d.URUTAN 
						
					UNION ALL
					
					SELECT b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						NVL(SUM(NILAIPENDAPATAN), 0) KOMISIAGENRP, b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, 
						f.NAMAUNITPRODUKSI, d.URUTAN 
					FROM TABEL_404_PENDAPATAN_LAIN_AGEN a 
					INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN AND a.KDKANTOR = b.KDKANTOR 
					INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
					LEFT OUTER JOIN TABEL_413_JABATAN_AGEN d ON b.KDJABATANAGEN = d.KDJABATANAGEN 
					LEFT OUTER JOIN TABEL_410_AREA_OFFICE e ON b.KDAREAOFFICE = e.KDAREAOFFICE AND b.KDKANTOR = e.KDKANTOR 
					LEFT OUTER JOIN TABEL_410_KODE_UNIT_PRODUKSI f ON b.KDKANTOR = f.KDKANTOR AND b.KDAREAOFFICE = f.KDAREAOFFICE 
						AND b.KDUNITPRODUKSI = f.KDUNITPRODUKSI 
					WHERE KDAUTHORISASI = 1 AND a.KDKANTOR = '$p' AND a.TGLPROSES BETWEEN TO_DATE('$p1', 'DD/MM/YYYY') 
						AND TO_DATE('$p2', 'DD/MM/YYYY')
						AND b.KDSTATUSAGEN = '01'
					GROUP BY b.PREFIXAGEN, a.NOAGEN, c.NAMAKLIEN1, b.KDJABATANAGEN, d.NAMAJABATANAGEN, NOREKENING, 
						a.NILAIPENDAPATAN, b.KDAREAOFFICE, e.NAMAAREAOFFICE, b.KDUNITPRODUKSI, f.NAMAUNITPRODUKSI, d.URUTAN
				) temp 
				GROUP BY PREFIXAGEN, NOAGEN, NAMAKLIEN1, KDJABATANAGEN, NAMAJABATANAGEN, NOREKENING, KDAREAOFFICE, 
					NAMAAREAOFFICE, KDUNITPRODUKSI, NAMAUNITPRODUKSI, URUTAN 
				ORDER BY URUTAN ASC, KDAREAOFFICE ASC NULLS FIRST, KDUNITPRODUKSI ASC NULLS FIRST";
		
		$DB->parse($sql);
		$DB->execute();
		
		echo json_encode($DB->result());
		//echo $sql;
	}
	
	
	/*===== tarik pendapatan agen sebawahnya =====*/
	if (strcasecmp($r, '4') == 0) {
		//$office1 = !empty($p5) ? " AND b.KDAREAOFFICE = '$p5' " : null;
		$office1 = null;
		$unit1 = !empty($p6) ? " AND b.KDUNITPRODUKSI = '$p6' " : null;
		$noagen = !empty($p7) ? " AND b.NOAGEN = '$p7' " : null;
		
		$sql = "SELECT a.PREFIXPERTANGGUNGAN, a.NOPERTANGGUNGAN, i.NAMAKLIEN1 NAMAPEMPOL, a.NOAGEN, e.NAMAJABATANAGEN, c.NAMAKLIEN1, 
					NOREKENING, NAMAKOMISIAGEN, 
					CASE WHEN KDJENISCB = 'B' THEN 'Berkala' WHEN KDJENISCB = 'X' THEN 'Sekaligus' ELSE KDJENISCB END CARABAYAR, 
					THNKOMISI, NVL(KOMISIAGENRP, 0) KOMISIAGENRP, TO_CHAR(a.TGLBOOKED, 'DD/MM/YYYY') TGLBOOKED, 
					TO_CHAR(a.TGLPROSES, 'DD/MM/YYYY') TGLPROSES, e.URUTAN, b.KDAREAOFFICE, f.NAMAAREAOFFICE, b.KDUNITPRODUKSI, 
					g.NAMAUNITPRODUKSI, b.KDJABATANAGEN, a.TGLPROSES TGLPERIODE 
				FROM TABEL_404_KOMISI_AGEN a 
				INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN 
				INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
				INNER JOIN TABEL_402_KODE_KOMISI_AGEN d ON a.KDKOMISIAGEN = d.KDKOMISIAGEN 
				INNER JOIN TABEL_413_JABATAN_AGEN e ON b.KDJABATANAGEN = e.KDJABATANAGEN 
				LEFT OUTER JOIN TABEL_410_AREA_OFFICE f ON b.KDKANTOR = f.KDKANTOR AND b.KDAREAOFFICE = f.KDAREAOFFICE 
				LEFT OUTER JOIN TABEL_410_KODE_UNIT_PRODUKSI g ON b.KDKANTOR = g.KDKANTOR AND b.KDAREAOFFICE = g.KDAREAOFFICE 
					AND b.KDUNITPRODUKSI = g.KDUNITPRODUKSI 
				INNER JOIN TABEL_200_PERTANGGUNGAN h ON a.PREFIXPERTANGGUNGAN = h.PREFIXPERTANGGUNGAN 
					AND a.NOPERTANGGUNGAN = h.NOPERTANGGUNGAN
				INNER JOIN TABEL_100_KLIEN i ON h.NOPEMEGANGPOLIS = i.NOKLIEN
				WHERE a.KDKOMISIAGEN != '10' AND KDAUTHORISASI = '2' AND a.KDRAYONPENAGIHAN = '$p' 
					AND b.KDSTATUSAGEN = '01' 
					AND a.TGLUPDATED BETWEEN TO_DATE('$p2', 'DD/MM/YYYY') AND TO_DATE('$p3', 'DD/MM/YYYY') 
					$office1 
					$unit1 
					$noagen 
					AND e.URUTAN >= (SELECT URUTAN FROM TABEL_413_JABATAN_AGEN a INNER JOIN TABEL_400_AGEN b ON a.KDJABATANAGEN = b.KDJABATANAGEN WHERE b.NOAGEN = '$p4')
					
				UNION ALL
				
				SELECT NULL, NULL, NULL, a.NOAGEN, e.NAMAJABATANAGEN, c.NAMAKLIEN1, NOREKENING, NAMAKOMISIAGEN, NULL, NULL, 
					NILAIPENDAPATAN, NULL, TO_CHAR(a.TGLPROSES, 'DD/MM/YYYY') TGLPROSES, e.URUTAN, b.KDAREAOFFICE, 
					f.NAMAAREAOFFICE, b.KDUNITPRODUKSI, g.NAMAUNITPRODUKSI, b.KDJABATANAGEN, a.TGLPROSES TGLPERIODE 
				FROM TABEL_404_PENDAPATAN_LAIN_AGEN a 
				INNER JOIN TABEL_400_AGEN b ON a.NOAGEN = b.NOAGEN AND a.KDKANTOR = b.KDKANTOR 
				INNER JOIN TABEL_100_KLIEN c ON a.NOAGEN = c.NOKLIEN 
				INNER JOIN TABEL_402_KODE_KOMISI_AGEN d ON a.KDKOMISIAGEN = d.KDKOMISIAGEN 
				INNER JOIN TABEL_413_JABATAN_AGEN e ON b.KDJABATANAGEN = e.KDJABATANAGEN 
				LEFT OUTER JOIN TABEL_410_AREA_OFFICE f ON b.KDKANTOR = f.KDKANTOR AND b.KDAREAOFFICE = f.KDAREAOFFICE 
				LEFT OUTER JOIN TABEL_410_KODE_UNIT_PRODUKSI g ON b.KDKANTOR = g.KDKANTOR AND b.KDAREAOFFICE = g.KDAREAOFFICE 
					AND b.KDUNITPRODUKSI = g.KDUNITPRODUKSI
				WHERE KDAUTHORISASI = 1 AND a.KDKANTOR = '$p' 
					AND b.KDSTATUSAGEN = '01' 
					AND a.TGLPROSES BETWEEN TO_DATE('$p2', 'DD/MM/YYYY') AND TO_DATE('$p3', 'DD/MM/YYYY')
					$office1 
					$unit1 
					$noagen
					AND e.URUTAN >= (SELECT URUTAN FROM TABEL_413_JABATAN_AGEN a INNER JOIN TABEL_400_AGEN b ON a.KDJABATANAGEN = b.KDJABATANAGEN WHERE b.NOAGEN = '$p4')
					
				UNION ALL
				
				SELECT NULL, NULL, NULL, NULL NOAGEN, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL URUTAN, 
					KDAREAOFFICE, NAMAAREAOFFICE, NULL KDUNITPRODUKSI, NULL NAMAUNITPRODUKSI, NULL KDJABATANAGEN, NULL TGLPERIODE 
				FROM TABEL_410_AREA_OFFICE b
				WHERE KDKANTOR = '$p' AND STATUS IS NULL $office1 
				
				UNION ALL
				
				SELECT NULL, NULL, NULL, NULL NOAGEN, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL URUTAN, 
					a.KDAREAOFFICE, NAMAAREAOFFICE, KDUNITPRODUKSI, NAMAUNITPRODUKSI, NULL KDJABATANAGEN, NULL TGLPERIODE
				FROM TABEL_410_AREA_OFFICE a 
				INNER JOIN TABEL_410_KODE_UNIT_PRODUKSI b ON a.KDKANTOR = b.KDKANTOR AND a.KDAREAOFFICE = b.KDAREAOFFICE 
				WHERE a.STATUS IS NULL AND b.STATUS IS NULL AND a.KDKANTOR = '$p' $office1 $unit1
				
				ORDER BY KDAREAOFFICE ASC NULLS FIRST, KDUNITPRODUKSI ASC NULLS FIRST, URUTAN ASC NULLS FIRST, NOAGEN ASC, TGLPERIODE";
		
		$DB->parse($sql);
		$DB->execute();
		
		echo json_encode($DB->result());
		//echo $sql;
	}
	
	/*===== tarik data Untuk Slip Gaji agen LPA =====*/
	if (strcasecmp($r, '5') == 0) {
		
		$sql = " select (select NILAIPENDAPATAN 
			FROM TABEL_404_PENDAPATAN_LAIN_AGEN 
			WHERE TO_CHAR(TGLUPDATED,'ddmmyyyy') = '$p1' and KDAUTHORISASI = '1'
			and KDKOMISIAGEN = '$p' 
			and NOAGEN = A.NOAGEN ) AS PENDAPATAN,
			(select NILAIPENDAPATAN 
			FROM TABEL_404_PENDAPATAN_LAIN_AGEN 
			WHERE TO_CHAR(TGLUPDATED,'ddmmyyyy') = '$p1' and KDAUTHORISASI = '1' 
			and KDKOMISIAGEN = 'F4' 
			and NOAGEN = A.NOAGEN) AS LISENSI,
			(select pajak 
			FROM TABEL_405_PAJAK_KOMISI_AGEN_N 
			WHERE TANGGAL = TO_DATE('$p1','ddmmyyyy') 
			AND NOAGEN = A.NOAGEN) AS PAJAK, 
			NOREKENING, 
			(select NAMABANK FROM TABEL_399_BANK WHERE KDBANK = a.NAMABANK) as NAMABANK,
			(SELECT NAMAKLIEN1 FROM TABEL_100_KLIEN WHERE NOKLIEN = a.noagen) namaklien
		FROM TABEL_400_AGEN A
		WHERE NOAGEN = '$p2'
		";

		$DB->parse($sql);
		$DB->execute();
		
		echo json_encode($DB->result());
		//echo $sql;
	}
	
	/*===== tarik data pendapatan agen LPA  =====*/
	if (strcasecmp($r, '6') == 0) {
		$tanggal = $p1;
		$sql = "select a.noagen, 
				to_char(tglproses,'dd/mm/yyyy') as tglproses, 
				to_char(a.TGLUPDATED,'ddmmyyyy') as tglbilling, 
				kdkomisiagen, 
				kdrekening, 
				nilaipendapatan, 
				KDAUTHORISASI, 
				KDSTATUSAGEN,
				(select namakomisiagen from tabel_402_kode_komisi_agen where a.kdkomisiagen = kdkomisiagen) as namakomisi,
				(select sum(fyp) from tabel_400_produksi_lpa m where a.noagen = m.noagen and a.tglproses = m.tglperiode and JENIS_REMUNERASI = a.kdkomisiagen ) as jmlfyp
				from tabel_404_pendapatan_lain_agen a
				inner join tabel_400_agen b on a.noagen = b.noagen
				where a.noagen = '$p'
				And KDAUTHORISASI = '1'
				and kdkomisiagen not in ('F4')
				$tanggal
				order by a.noagen, kdkomisiagen asc 
		";
		
		$DB->parse($sql);
		$DB->execute();
		
		echo json_encode($DB->result());
		//echo $sql;
	}