sudo mv ./klaim/loadpengajuanklaim.php ./klaim/loadpengajuanklaim.php.rollback.16022023 && \
sudo mv ./mbah/input_extrapremi.php ./mbah/input_extrapremi.php.rollback.16022023 && \
sudo mv ./pelaporan/infopoliskantor.php ./pelaporan/infopoliskantor.php.rollback.16022023 && \
sudo mv ./pelaporan/rekapWelcomingCall.php ./pelaporan/rekapWelcomingCall.php.rollback.16022023 && \
sudo mv ./polis/mutasi.php ./polis/mutasi.php.rollback.16022023 && \
sudo mv ./produksikantor.php ./produksikantor.php.rollback.16022023 && \
sudo mv ./proposal/ulink/benefit.php ./proposal/ulink/benefit.php.rollback.16022023 && \
sudo mv ./proposal/ulink/cektinggiberat.php ./proposal/ulink/cektinggiberat.php.rollback.16022023 && \
sudo mv ./proposal/ulink/chainselectors.php ./proposal/ulink/chainselectors.php.rollback.16022023 && \
sudo mv ./proposal/ulink/get_data_rider.php ./proposal/ulink/get_data_rider.php.rollback.16022023 && \
sudo mv ./proposal/ulink/hitungusia1.php ./proposal/ulink/hitungusia1.php.rollback.16022023 && \
sudo mv ./proposal/ulink/includes/ntryprop.js ./proposal/ulink/includes/ntryprop.js.rollback.16022023 && \
sudo mv ./proposal/ulink/insprop.php ./proposal/ulink/insprop.php.rollback.16022023 && \
sudo mv ./proposal/ulink/lapcabang.php ./proposal/ulink/lapcabang.php.rollback.16022023 && \
sudo mv ./proposal/ulink/ntryprop_ulink.php ./proposal/ulink/ntryprop_ulink.php.rollback.16022023 && \
sudo mv ./proposal/ulink/spajlist.php ./proposal/ulink/spajlist.php.rollback.16022023 && \
sudo mv ./proposal/ulink/test.cetak.polis.linknew.php ./proposal/ulink/test.cetak.polis.linknew.php.rollback.16022023 && \
sudo mv ./proposal/welcomingcall.php ./proposal/welcomingcall.php.rollback.16022023 && \
sudo mv ./report/report_nilai_tunai/cetak_nilai_tunai.php ./report/report_nilai_tunai/cetak_nilai_tunai.php.rollback.16022023 && \
sudo mv ./report/report_nilai_tunai/function.gen.email.php ./report/report_nilai_tunai/function.gen.email.php.rollback.16022023 && \
sudo mv ./klaim/loadpengajuanklaim.php.bak.16022023 ./klaim/loadpengajuanklaim.php && \
sudo mv ./mbah/input_extrapremi.php.bak.16022023 ./mbah/input_extrapremi.php && \
sudo mv ./pelaporan/infopoliskantor.php.bak.16022023 ./pelaporan/infopoliskantor.php && \
sudo mv ./pelaporan/rekapWelcomingCall.php.bak.16022023 ./pelaporan/rekapWelcomingCall.php && \
sudo mv ./polis/mutasi.php.bak.16022023 ./polis/mutasi.php && \
sudo mv ./produksikantor.php.bak.16022023 ./produksikantor.php && \
sudo mv ./proposal/ulink/benefit.php.bak.16022023 ./proposal/ulink/benefit.php && \
sudo mv ./proposal/ulink/cektinggiberat.php.bak.16022023 ./proposal/ulink/cektinggiberat.php && \
sudo mv ./proposal/ulink/chainselectors.php.bak.16022023 ./proposal/ulink/chainselectors.php && \
sudo mv ./proposal/ulink/get_data_rider.php.bak.16022023 ./proposal/ulink/get_data_rider.php && \
sudo mv ./proposal/ulink/hitungusia1.php.bak.16022023 ./proposal/ulink/hitungusia1.php && \
sudo mv ./proposal/ulink/includes/ntryprop.js ./proposal/ulink/includes/ntryprop.js && \
sudo mv ./proposal/ulink/insprop.php.bak.16022023 ./proposal/ulink/insprop.php && \
sudo mv ./proposal/ulink/lapcabang.php.bak.16022023 ./proposal/ulink/lapcabang.php && \
sudo mv ./proposal/ulink/ntryprop_ulink.php.bak.16022023 ./proposal/ulink/ntryprop_ulink.php && \
sudo mv ./proposal/ulink/spajlist.php.bak.16022023 ./proposal/ulink/spajlist.php && \
sudo mv ./proposal/ulink/test.cetak.polis.linknew.php.bak.16022023 ./proposal/ulink/test.cetak.polis.linknew.php && \
sudo mv ./proposal/welcomingcall.php.bak.16022023 ./proposal/welcomingcall.php && \
sudo mv ./report/report_nilai_tunai/cetak_nilai_tunai.php.bak.16022023 ./report/report_nilai_tunai/cetak_nilai_tunai.php && \
sudo mv ./report/report_nilai_tunai/function.gen.email.php.bak.16022023 ./report/report_nilai_tunai/function.gen.email.php
