sudo mv ./api/jsspaj/application/config/autoload.php ./api/jsspaj/application/config/autoload.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/config/constants.php ./api/jsspaj/application/config/constants.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/config/rest.php ./api/jsspaj/application/config/rest.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/Controllers/Master.php ./api/jsspaj/application/Controllers/Master.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/controllers/Pos.php ./api/jsspaj/application/controllers/Pos.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/models/Mmaster.php ./api/jsspaj/application/models/Mmaster.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/models/Mpos.php ./api/jsspaj/application/models/Mpos.php.rollback.16022023 && \
sudo mv ./api/spajonline_v1/js/controllers.js ./api/spajonline_v1/js/controllers.js.rollback.16022023 && \
sudo mv ./api/spajonline_v1/js/services.js ./api/spajonline_v1/js/services.js.rollback.16022023 && \
sudo mv ./api/spajonline_v1/js/services.min.js ./api/spajonline_v1/js/services.min.js.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/daftarSPAJOnline.html ./api/spajonline_v1/templates/daftarSPAJOnline.html.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/lembarPersetujuan.html ./api/spajonline_v1/templates/lembarPersetujuan.html.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/pekerjaanPemegangPolis.html ./api/spajonline_v1/templates/pekerjaanPemegangPolis.html.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/sKKTertanggung.html ./api/spajonline_v1/templates/sKKTertanggung.html.rollback.16022023 && \
sudo mv ./application/controller/Prospek.php ./application/controller/Prospek.php.rollback.16022023 && \
sudo mv ./application/models/Prospek_model.php ./application/models/Prospek_model.php.rollback.16022023 && \
sudo mv ./application/views/master_page.php ./application/views/master_page.php.rollback.16022023 && \
sudo mv ./application/views/prospek/follow_up.php ./application/views/prospek/follow_up.php.rollback.16022023 && \
sudo mv ./application/views/prospek/proposal.php ./application/views/prospek/proposal.php.rollback.16022023 && \
sudo mv ./application/views/prospek/uploadfile.php ./application/views/prospek/uploadfile.php.rollback.16022023 && \
sudo mv ./application/views/prospek/uploadfile_recording.php ./application/views/prospek/uploadfile_recording.php.rollback.16022023 && \
sudo mv ./application/views/spajonline/cetak.php ./application/views/spajonline/cetak.php.rollback.16022023 && \
sudo mv ./application/views/spajonline/dashboard.php ./application/views/spajonline/dashboard.php.rollback.16022023 && \
sudo mv ./mobileapi/spaj_bridge/get.php ./mobileapi/spaj_bridge/get.php.rollback.16022023 && \
sudo mv ./simulasi/application/controllers/jspromapannew_2019.php ./simulasi/application/controllers/jspromapannew_2019.php.rollback.16022023 && \
sudo mv ./simulasi/application/controllers/produk.php ./simulasi/application/controllers/produk.php.rollback.16022023 && \
sudo mv ./simulasi/application/views/hasil/jspromapanifg.php ./simulasi/application/views/hasil/jspromapanifg.php.rollback.16022023 && \
sudo mv ./simulasi/application/views/pdf/lifeprimeifg.php ./simulasi/application/views/pdf/lifeprimeifg.php.rollback.16022023 && \
sudo mv ./simulasi/application/views/produk/lifeprotect.php ./simulasi/application/views/produk/lifeprotect.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/helpers/respon_helper.php ./api/jsspaj/application/helpers/respon_helper.php.rollback.16022023 && \

sudo mv ./api/jsspaj/application/config/autoload.php.bak.16022023 ./api/jsspaj/application/config/autoload.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/config/constants.php.bak.16022023 ./api/jsspaj/application/config/constants.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/config/rest.php.bak.16022023 ./api/jsspaj/application/config/rest.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/Controllers/Master.php.bak.16022023 ./api/jsspaj/application/Controllers/Master.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/controllers/Pos.php.bak.16022023 ./api/jsspaj/application/controllers/Pos.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/models/Mmaster.php.bak.16022023 ./api/jsspaj/application/models/Mmaster.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/models/Mpos.php.bak.16022023 ./api/jsspaj/application/models/Mpos.php.rollback.16022023 && \
sudo mv ./api/spajonline_v1/js/controllers.js.bak.16022023 ./api/spajonline_v1/js/controllers.js.rollback.16022023 && \
sudo mv ./api/spajonline_v1/js/services.js.bak.16022023 ./api/spajonline_v1/js/services.js.rollback.16022023 && \
sudo mv ./api/spajonline_v1/js/services.min.js.bak.16022023 ./api/spajonline_v1/js/services.min.js.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/daftarSPAJOnline.html.bak.16022023 ./api/spajonline_v1/templates/daftarSPAJOnline.html.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/lembarPersetujuan.html.bak.16022023 ./api/spajonline_v1/templates/lembarPersetujuan.html.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/pekerjaanPemegangPolis.html.bak.16022023 ./api/spajonline_v1/templates/pekerjaanPemegangPolis.html.rollback.16022023 && \
sudo mv ./api/spajonline_v1/templates/sKKTertanggung.html.bak.16022023 ./api/spajonline_v1/templates/sKKTertanggung.html.rollback.16022023 && \
sudo mv ./application/controller/Prospek.php.bak.16022023 ./application/controller/Prospek.php.rollback.16022023 && \
sudo mv ./application/models/Prospek_model.php.bak.16022023 ./application/models/Prospek_model.php.rollback.16022023 && \
sudo mv ./application/views/master_page.php.bak.16022023 ./application/views/master_page.php.rollback.16022023 && \
sudo mv ./application/views/prospek/follow_up.php.bak.16022023 ./application/views/prospek/follow_up.php.rollback.16022023 && \
sudo mv ./application/views/prospek/proposal.php.bak.16022023 ./application/views/prospek/proposal.php.rollback.16022023 && \
sudo mv ./application/views/prospek/uploadfile.php.bak.16022023 ./application/views/prospek/uploadfile.php.rollback.16022023 && \
sudo mv ./application/views/prospek/uploadfile_recording.php.bak.16022023 ./application/views/prospek/uploadfile_recording.php.rollback.16022023 && \
sudo mv ./application/views/spajonline/cetak.php.bak.16022023 ./application/views/spajonline/cetak.php.rollback.16022023 && \
sudo mv ./application/views/spajonline/dashboard.php.bak.16022023 ./application/views/spajonline/dashboard.php.rollback.16022023 && \
sudo mv ./mobileapi/spaj_bridge/get.php.bak.16022023 ./mobileapi/spaj_bridge/get.php.rollback.16022023 && \
sudo mv ./simulasi/application/controllers/jspromapannew_2019.php.bak.16022023 ./simulasi/application/controllers/jspromapannew_2019.php.rollback.16022023 && \
sudo mv ./simulasi/application/controllers/produk.php.bak.16022023 ./simulasi/application/controllers/produk.php.rollback.16022023 && \
sudo mv ./simulasi/application/views/hasil/jspromapanifg.php.bak.16022023 ./simulasi/application/views/hasil/jspromapanifg.php.rollback.16022023 && \
sudo mv ./simulasi/application/views/pdf/lifeprimeifg.php.bak.16022023 ./simulasi/application/views/pdf/lifeprimeifg.php.rollback.16022023 && \
sudo mv ./simulasi/application/views/produk/lifeprotect.php.bak.16022023 ./simulasi/application/views/produk/lifeprotect.php.rollback.16022023 && \
sudo mv ./api/jsspaj/application/helpers/respon_helper.php.bak.16022023 ./api/jsspaj/application/helpers/respon_helper.php.rollback.16022023